# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Daniel Hodgins personal website
#email:
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal website of Daniel Hodgins.
twitter_username: DanielHodgins3
github_username: DanielHodgins

search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Daniel Hodgins"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Daniel Hodgins is a PHD student at Auburn in the Department of Mathematics and Statistics. He holds a Master of Science in Mathematics and in his undergrad he double majored in Mechanical Engineeringand Mathematicswith a concentration in Aerospace Engineering."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://danielhodgins.github.io/"
    - label: "Twitter"
      icon: "fab fa-brands fa-x-twitter"
      url: "https://x.com/DanielHodgins3"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DanielHodgins"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/danielhodgins9391/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-brands fa-x-twitter"
      url: "https://x.com/DanielHodgins3"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DanielHodgins"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/danielhodgins9391/"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


