# Site settings
title: "Daniel's Webpage"
description: "test site"
baseurl: ""
url: ""

# CSS settings
css:
  body:
    font-family: '"Times New Roman", Times, serif'
    margin: 0
    padding: 0
    background-color: '#f0f0f0'
  
  header:
    position: relative
    background-color: '#333'
    color: '#fff'
    padding: '30px 20px'
    text-align: center
    height: auto
  
  footer:
    position: relative
    background-color: '#333'
    color: '#fff'
    padding: '30px 20px'
    text-align: center
    height: auto

  favicon:
    position: absolute
    top: '10px'
    left: '10px'
    height: '90%'

  nav:
    position: relative
    height: '5%'
    background-color: '#444'
    padding: '10px'
    text-align: center

  nav ul:
    list-style-type: none
    margin: 0
    padding: 0
    text-align: center

  nav ul li:
    display: inline
    margin-right: '20px'

  nav ul li a:
    text-decoration: none
    color: '#fff'
  
  nav ul li a:hover:
    color: '#ddd'

  content:
    padding: '20px'
    text-align: left
    font-family: '"Times New Roman", Times, serif'
    background-color: '#f0f0f0'

  cloud:
    width: '90% !important'
    background-color: '#fff'
    padding: '20px'
    border-radius: '10px'
    box-shadow: '0 0 50px rgba(0, 0, 0, 0.5)'
    text-align: justify
    overflow: hidden
    margin: auto

  navcloud:
    width: 'fit-content+10px'
    height: 'auto + 10px'
    padding: '10px'
    border-radius: '25%'
    background-color: '#111'
    display: inline-block

  download-cv:
    margin-top: '20px'
    text-align: justify

  download-cv a:
    display: inline-block
    padding: '10px 20px'
    background-color: '#333'
    color: '#fff'
    text-decoration: none
    border-radius: '5px'
    transition: 'background-color 0.3s'
  
  download-cv a:hover:
    background-color: '#555'

  list-inline.social:
    padding: 0
    list-style: none

  list-inline.social li:
    display: inline-block
    margin-right: '10px'
  
  list-inline.social li:last-child:
    margin-right: 0

  ul:
    text-align: left
  
  ul li:
    text-align: left

# Media queries
media:
  max-width-700px:
    favicon:
      position: absolute
      top: '10px'
      left: '10px'
      height: auto
      width: '20%'
    header:
      background-color: '#AAAAFF'
