# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Home Page
#email:
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal website of Daniel Hodgins.
twitter_username: DanielHodgins3
github_username: DanielHodgins
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Daniel Hodgins"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Daniel Hodgins is a PHD student at Auburn in the Department of Mathematics and Statistics. He holds a Master of Science in Mathematics and in his undergrad he double majored in Mechanical Engineeringand Mathematicswith a concentration in Aerospace Engineering."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://danielhodgins.github.io/"
    - label: "Twitter"
      icon: "fab fa-brands fa-x-twitter"
      url: "https://x.com/DanielHodgins3"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DanielHodgins"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/danielhodgins9391/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-brands fa-x-twitter"
      url: "https://x.com/DanielHodgins3"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DanielHodgins"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/danielhodgins9391/"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

  # CSS settings
css:
  body:
    font-family: '"Times New Roman", Times, serif'
    margin: 0
    padding: 0
    background-color: '#f0f0f0'
  
  header:
    position: relative
    background-color: '#333'
    color: '#fff'
    padding: '30px 20px'
    text-align: center
    height: auto
  
  footer:
    position: relative
    background-color: '#333'
    color: '#fff'
    padding: '30px 20px'
    text-align: center
    height: auto

  favicon:
    position: absolute
    top: '10px'
    left: '10px'
    height: '90%'

  nav:
    position: relative
    height: '5%'
    background-color: '#444'
    padding: '10px'
    text-align: center

  nav ul:
    list-style-type: none
    margin: 0
    padding: 0
    text-align: center

  nav ul li:
    display: inline
    margin-right: '20px'

  nav ul li a:
    text-decoration: none
    color: '#fff'
  
  nav ul li a:hover:
    color: '#ddd'

  content:
    padding: '20px'
    text-align: left
    font-family: '"Times New Roman", Times, serif'
    background-color: '#f0f0f0'

  cloud:
    width: '90% !important'
    background-color: '#fff'
    padding: '20px'
    border-radius: '10px'
    box-shadow: '0 0 50px rgba(0, 0, 0, 0.5)'
    text-align: justify
    overflow: hidden
    margin: auto

  navcloud:
    width: 'fit-content+10px'
    height: 'auto + 10px'
    padding: '10px'
    border-radius: '25%'
    background-color: '#111'
    display: inline-block

  download-cv:
    margin-top: '20px'
    text-align: justify

  download-cv a:
    display: inline-block
    padding: '10px 20px'
    background-color: '#333'
    color: '#fff'
    text-decoration: none
    border-radius: '5px'
    transition: 'background-color 0.3s'
  
  download-cv a:hover:
    background-color: '#555'

  list-inline.social:
    padding: 0
    list-style: none

  list-inline.social li:
    display: inline-block
    margin-right: '10px'
  
  list-inline.social li:last-child:
    margin-right: 0

  ul:
    text-align: left
  
  ul li:
    text-align: left

# Media queries
media:
  max-width-700px:
    favicon:
      position: absolute
      top: '10px'
      left: '10px'
      height: auto
      width: '20%'
    header:
      background-color: '#AAAAFF'
